### ISSUE TITLE
Entity Component System stops updating

### ISSUE THREAD

**Issue by MAHines** [sarangborude/Bubbles#1]
As described in the file comments, I modified ImmersiveView.swift and BubblesApp.swift to use the Entity Component System. I then changed speed in BubblesSystem.swift to 0.001 to make the physics more apparent. When I compile and run the app, the bubbles move for a second or two, then freeze in place. This behavior is unexpected, as the bubbles should continue to propagate forever.

I had the same problem with the code that I generated when following the YouTube tutorial.

**Comment by sarangborude** [comment]
Thanks for pointing this out..
I just realized that it is better to use this when updating the system so I am pushing an update to resolve this
<img width="818" alt="image" src="https://github.com/user-attachments/assets/dbec13d1-7eda-419c-9cdd-7ee29c199567">
